### PR TITLE
Update README.md for build steps

### PR DESCRIPTION
**Pull request by edel-macias-cubix**
Added note for then the module is not found.

### CODE REVIEW

**Comment by dmazzella** [comment]
Thanks, for contribution, i have added explicit example for [esp32](https://github.com/dmazzella/ucrypto/commit/baa814c22ccbc22535053ac1b66e09fad4e4a376)

**Comment by officer47p** [comment]
This thing should be in the README file, not everyone is building for esp32.
I have been trying to build for pico like hours, and not I found the solution to the error in a closed PR.

**Comment by dmazzella** [comment]
@officer47p i have updated the readme for [arduino_nano_rp2040_connect](https://github.com/dmazzella/ucrypto?tab=readme-ov-file#arduino_nano_rp2040_connect)

**Comment by officer47p** [comment]
@dmazzella Damn... That was fast 🤯 😅 
Thank you so much man 🌹

**Pull request closed without merging**
